# **AIN 214 - PA1 - FALL 2025**

**Student ID** : 2230765012

**Name-Surname**   : Koray Solakoğlu

**Deadline: 3.11.2025 (23:59:59)**

**Submission:** Submit your Jupyter Notebooks via https://submit.cs.hacettepe.edu.tr/

# **Necessary Imports**

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import sqlite3

# **Notes:**

* Use pandas dataframe (df) to load the data.

* Use numpy or pandas operations for the requested tasks unless otherwise specified.

* You can insert more cells if it is necessary.

# **PART 1: Flight Delays and Cancellations Dataset**

The US Department of Transportation's Bureau of Transportation.

**Dataset Path: "datasets/flights_dataset/*.csv"**

- `flights.csv` contains the flight information

| Variable   | Description                                          |
|------------|------------------------------------------------------|
| `year`, `month`, `day` | The time information of the flight |
| `dep_time`   | Departure time (in the format hhmm) where`NA` corresponds to a cancelled flight        |
| `sched_dep_time`    | Scheduled departure time                        |
| `dep_delay`  | Departure delay, in minutes (negative for early)    |
| `arr_time`  | Arrival time    |
| `sched_arr_time`  | Scheduled arrival time    |
| `arr_delay`  | Arrival delay, in minutes (negative for early)    |
| `carrier`  | Carrier/airline code    |
| `tailnum`  | Tail number of the plane    |
| `origin`     | Origin airport where flight starts (IATA code)
| `airline`    | Carrier/airline name                        |
| `dest`       | Destination airport where flight lands (IATA code)  |
| `air_time`    | The duration of flight (on air)                       |
| `distance`    | The distance between origin and destination airports (miles)                        |
| `hour`, `minute`, `time_hour`    | Time information of the flight                       

- `flights_weather.csv` contains the same flight information as well as weather conditions such as

| Variable   | Description                                           |
|------------|-------------------------------------------------------|
| `visib`      | Visibility (in miles)                                 |
| `wind_gust`  | Wind gust speed (in mph)

### Load & Inspect the Data (15 pts)

Load `flights.csv` as `flights_df` and `flights_weather.csv` as `weather_df` by using pandas DataFrame. (2 pts)

In [3]:
# Load the data
flights_df = pd.read_csv("datasets/flights_dataset/flights.csv")
weather_df = pd.read_csv("datasets/flights_dataset/flights_weather.csv")

Show the first and the last five rows of the datasets. (4 pts)

In [4]:
# flights_df
display(flights_df.head())
display(flights_df.tail())

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,555,N405UA,SEA,IAH,221.0,1874,23,59,2022-01-01T23:00:00Z,United Air Lines Inc.
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,72,N265AK,SEA,FAI,193.0,1533,22,50,2022-01-01T22:00:00Z,Alaska Airlines Inc.
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,270,N274AK,SEA,ATL,261.0,2182,23,55,2022-01-01T23:00:00Z,Alaska Airlines Inc.
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,7,N281AK,SEA,ORD,193.0,1721,23,50,2022-01-01T23:00:00Z,Alaska Airlines Inc.
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,507,N426UA,PDX,ORD,196.0,1739,23,49,2022-01-01T23:00:00Z,United Air Lines Inc.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,airline
111371,2022,6,30,NaN,1155,NaN,NaN,2033,NaN,UA,206,NaN,SEA,EWR,NaN,2402,11,55,2022-06-30T11:00:00Z,United Air Lines Inc.
111372,2022,6,30,NaN,1448,NaN,NaN,1732,NaN,DL,323,N3759,SEA,LAX,NaN,954,14,48,2022-06-30T14:00:00Z,Delta Air Lines Inc.
111373,2022,6,30,NaN,1751,NaN,NaN,2352,NaN,DL,377,N898DN,SEA,ORD,NaN,1721,17,51,2022-06-30T17:00:00Z,Delta Air Lines Inc.
111374,2022,6,30,NaN,1145,NaN,NaN,2029,NaN,DL,114,N876DN,SEA,JFK,NaN,2422,11,45,2022-06-30T11:00:00Z,Delta Air Lines Inc.
111375,2022,6,30,NaN,720,NaN,NaN,1544,NaN,DL,168,N814DN,SEA,BOS,NaN,2496,7,20,2022-06-30T07:00:00Z,Delta Air Lines Inc.

In [5]:
# weather
display(weather_df.head())
display(weather_df.tail())

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,route,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
0,2022,1,1,1.0,2359,2.0,604.0,618,-14.0,UA,...,SEA-IAH,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
1,2022,1,1,1.0,2250,71.0,242.0,142,60.0,AS,...,SEA-FAI,32.0,23.0,69.04,170.0,9.20624,10.594357,0.0,1023.4,10.0
2,2022,1,1,10.0,2355,15.0,759.0,730,29.0,AS,...,SEA-ATL,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
3,2022,1,1,25.0,2350,35.0,606.0,550,16.0,AS,...,SEA-ORD,33.0,23.0,66.06,160.0,8.05546,9.270062,0.0,1022.9,10.0
4,2022,1,1,35.0,2349,46.0,616.0,545,31.0,UA,...,PDX-ORD,33.0,19.0,55.75,120.0,6.90468,7.945768,0.0,1025.1,10.0

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,route,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
111001,2022,6,30,NaN,1155,NaN,NaN,2033,NaN,UA,...,SEA-EWR,56.0,51.0,83.88,30.0,9.20624,10.594357,0.0,1021.5,10.0
111002,2022,6,30,NaN,1448,NaN,NaN,1732,NaN,DL,...,SEA-LAX,60.0,53.0,77.65,20.0,6.90468,7.945768,0.0,1021.9,10.0
111003,2022,6,30,NaN,1751,NaN,NaN,2352,NaN,DL,...,SEA-ORD,65.0,53.0,65.56,280.0,6.90468,7.945768,0.0,1021.3,10.0
111004,2022,6,30,NaN,1145,NaN,NaN,2029,NaN,DL,...,SEA-JFK,56.0,51.0,83.88,30.0,9.20624,10.594357,0.0,1021.5,10.0
111005,2022,6,30,NaN,720,NaN,NaN,1544,NaN,DL,...,SEA-BOS,56.0,50.0,80.52,350.0,5.75390,6.621473,0.0,1021.8,10.0

How many records(rows) exists on each dataset? Use print function for the answer. (2 pts)

In [6]:
# Show the number of records (rows) in each dataset.
print(len(flights_df))
print(len(weather_df))

111376
111006

What are the column types? Print columns and their datatypes. (2 pts)

In [7]:
# Show the data types for columns
print("Flights")
print(flights_df.dtypes)
print("Weather")
print(weather_df.dtypes)

Flights
year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier            object
flight              int64
tailnum            object
origin             object
dest               object
air_time          float64
distance            int64
hour                int64
minute              int64
time_hour          object
airline            object
dtype: object
Weather
year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier            object
flight              int64
tailnum            object
origin             object
dest               object
air_time          float64
distance            int64
hour                int64
minute              int64
airline            object
route              object
temp              float64
dewp              float64
humid             float64
wind_dir          float64
wind_speed        float64
wind_gust         float64
precip            float64
pressure          float64
visib             float64
dtype: object

Compute a missing value summary (count and %) per column for each dataset. (3 pts)

In [8]:
# Print the summary
print("Missing Value for flights_df")
missing_flights_count = flights_df.isnull().sum()
missing_flights_percent = (missing_flights_count / len(flights_df)) * 100
flights_summary = pd.DataFrame({
    'Missing Value Count': missing_flights_count,
    'Percentage (%)': missing_flights_percent
})
display(flights_summary)
print("Missing Value for weather_df")
missing_weather_count = weather_df.isnull().sum()
missing_weather_percent = (missing_weather_count / len(weather_df)) * 100
weather_summary = pd.DataFrame({
    'Missing Value Count': missing_weather_count,
    'Percentage (%)': missing_weather_percent
})
display(weather_summary)

Missing Value for flights_df

                Missing Value Count  Percentage (%)
year                              0        0.000000
month                             0        0.000000
day                               0        0.000000
dep_time                       2445        2.195266
sched_dep_time                    0        0.000000
dep_delay                      2445        2.195266
arr_time                       2542        2.282359
sched_arr_time                    0        0.000000
arr_delay                      2679        2.405366
carrier                           0        0.000000
flight                            0        0.000000
tailnum                         129        0.115824
origin                            0        0.000000
dest                              0        0.000000
air_time                       2679        2.405366
distance                          0        0.000000
hour                              0        0.000000
minute                            0        0.000000
time_hour                         0        0.000000
airline                           0        0.000000

Missing Value for weather_df

                Missing Value Count  Percentage (%)
year                              0        0.000000
month                             0        0.000000
day                               0        0.000000
dep_time                       2440        2.198079
sched_dep_time                    0        0.000000
dep_delay                      2440        2.198079
arr_time                       2537        2.285462
sched_arr_time                    0        0.000000
arr_delay                      2674        2.408879
carrier                           0        0.000000
flight                            0        0.000000
tailnum                         129        0.116210
origin                            0        0.000000
dest                              0        0.000000
air_time                       2674        2.408879
distance                          0        0.000000
hour                              0        0.000000
minute                            0        0.000000
airline                           0        0.000000
route                             0        0.000000
temp                              0        0.000000
dewp                              0        0.000000
humid                             0        0.000000
wind_dir                       3163        2.849396
wind_speed                      279        0.251338
wind_gust                       279        0.251338
precip                            0        0.000000
pressure                          0        0.000000
visib                             0        0.000000

Identify likely key columns for a potential merging between two datasets. (2 pts)

In [14]:
print("flights_df Columns:")
print(flights_df.columns)

print("\nweather_df Columns:")
print(weather_df.columns)
print("'year', 'month', 'day', 'hour' and 'origin' columns can be key columns.")

flights_df Columns:
Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour', 'airline'],
      dtype='object')

weather_df Columns:
Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'airline', 'route', 'temp', 'dewp', 'humid', 'wind_dir', 'wind_speed',
       'wind_gust', 'precip', 'pressure', 'visib'],
      dtype='object')
'year', 'month', 'day', 'hour' and 'origin' columns can be key columns.

### Data Exploration and Analysis (35 pts)

**Note:** You can create new columns, merge datasets or perform any other operations in this stage.

How many different airlines has flight records in the flights dataset? (2 pts)

In [10]:
# Answer the question above
different_airline_number = flights_df['airline'].nunique()
print(f"Different Airline Number = {different_airline_number}")

Different Airline Number = 12

Calculate the mean, min, max and std of the departure delay times. (Column: `dep_delay`) (2 pts)

In [11]:
# Answer the question above
print(f"Mean: {flights_df['dep_delay'].mean()}")
print(f"Max: {flights_df['dep_delay'].max()}")
print(f"Min: {flights_df['dep_delay'].min()}")
print(f"Std: {flights_df['dep_delay'].std()}")

Mean: 8.036674592173027
Max: 2120.0
Min: -36.0
Std: 41.65103180286961

Compute the summary statistics for weather columns. (`temperature`, `wind_speed`, `precipitation`) (2 pts)

In [12]:
# Answer the question above
print("Temperature Statistics")
print(weather_df['temp'].describe())
print()
print("Wind Speed Statistics")
print(weather_df['wind_speed'].describe())
print()
print("Precipitation Statistics")
print(weather_df['precip'].describe())

Temperature Statistics
count    111006.000000
mean         48.155538
std           9.363201
min          21.900000
25%          42.000000
50%          47.000000
75%          54.000000
max          99.000000
Name: temp, dtype: float64

Wind Speed Statistics
count    110727.000000
mean          6.995307
std           4.507431
min           0.000000
25%           4.603120
50%           6.904680
75%           9.206240
max          27.618720
Name: wind_speed, dtype: float64

Precipitation Statistics
count    111006.000000
mean          0.005774
std           0.022099
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.320000
Name: precip, dtype: float64

How many flights are delayed more than 15 minutes? Report count and the percentage. (3 pts)

In [13]:
# Answer the question above
delayed_flights = flights_df[ flights_df['dep_delay'] > 15]
delayed_flights_count = len(delayed_flights)
total_flights = len(flights_df)
percentage = (delayed_flights_count/total_flights) * 100
print(f"Count: {delayed_flights_count}")
print(f"Percentage: {percentage}")

Count: 17539
Percentage: 15.74755782215199

How many flights are cancelled in the dataset? (3 pts)

In [34]:
# Answer the question above
cancelled_flights_count = flights_df['dep_time'].isnull().sum()
print(f"Count: {cancelled_flights_count}")

Count: 2445

Report top 5 airlines has the most cancellation by count and percantage seperately. (3 pts)

In [35]:
# Answer the question above
cancelled_flights = flights_df[flights_df['dep_time'].isnull()]
sorted_cancel_counts = cancelled_flights['airline'].value_counts()
top_five = sorted_cancel_counts.head()
display(top_five)

airline
Alaska Airlines Inc.      1300
Delta Air Lines Inc.       383
Horizon Air                238
SkyWest Airlines Inc.      165
Southwest Airlines Co.     100
Name: count, dtype: int64

In [37]:
# Answer the question above
total_cancellation = len(cancelled_flights)
percentage = (top_five/total_cancellation)*100
display(percentage)

airline
Alaska Airlines Inc.      53.169734
Delta Air Lines Inc.      15.664622
Horizon Air                9.734151
SkyWest Airlines Inc.      6.748466
Southwest Airlines Co.     4.089980
Name: count, dtype: float64

Which airline has the highest departure delay average? And what is the average delay for the airline? (3 pts)

In [36]:
# Answer the question above
mean_values = flights_df.groupby('airline')['dep_delay'].mean()
sorted_values = mean_values.sort_values(ascending=False)
top_one = sorted_values.head(1)
display(top_one)

airline
JetBlue Airways    42.141524
Name: dep_delay, dtype: float64

Which routes has the most cancelled flights? Report top 10 routes and the number of cancelled flights. (Note: A route is "[origin]-[dest]". For example PDX-BUR) (4 pts)

In [37]:
# Answer the question above
cancelled_flights = flights_df[flights_df['dep_time'].isnull()].copy()
cancelled_flights['route'] = cancelled_flights['origin'] + '-' + cancelled_flights['dest']
sorted_routes = cancelled_flights['route'].value_counts()
top_ten = sorted_routes.head(10)
display(top_ten)

route
SEA-LAX    93
SEA-ANC    78
SEA-LAS    73
SEA-SFO    73
SEA-PDX    71
SEA-JFK    70
PDX-SEA    68
SEA-DEN    66
SEA-ORD    63
SEA-PHX    60
Name: count, dtype: int64

Which route has the highest average departure delay time? Report top 10 routes with the average departure delay times. (3 pts)

In [38]:
# Answer the question above
flights_df['route'] = flights_df['origin'] + '-' + flights_df['dest']
route_averages = flights_df.groupby('route')['dep_delay'].mean()
sorted_route_averages = route_averages.sort_values(ascending=False)
display(sorted_route_averages.head(10))

route
PDX-DSM    35.782609
PDX-GRR    35.739130
PDX-FLL    30.893617
SEA-MIA    29.916667
SEA-CLT    27.313199
PDX-STL    27.000000
PDX-BOS    24.812500
PDX-DFW    24.735941
PDX-DAL    24.100000
PDX-JFK    21.729433
Name: dep_delay, dtype: float64

Compare mean departure delay between rainy and non-rainy flights. (5 pts)

Tip: Check `precip` column in weather dataset

In [16]:
# Answer the question above
merged_df = pd.merge(flights_df, weather_df, on=['year', 'month', 'day', 'hour', 'origin'])
rainy_flights = merged_df[merged_df['precip'] > 0 ]
non_rainy_flights = merged_df[merged_df['precip'] == 0 ]
mean_delay_rainy = rainy_flights['dep_delay_x'].mean()
mean_delay_non_rainy = non_rainy_flights['dep_delay_x'].mean()
print(f"Rainy Flights Delay: {mean_delay_rainy}")
print(f"Non-rainy Flights Delay: {mean_delay_non_rainy}")

Rainy Flights Delay: 9.890659058132227
Non-rainy Flights Delay: 7.485282517716174

Compare mean departure delay between wind condition. Consider 10 mile per hour or more wind gust is considered as windy. (5 pts)

In [17]:
# Answer the question above
merged_df['wind_gust'] = merged_df['wind_gust'].fillna(0)
windy_flights = merged_df[ merged_df['wind_gust'] >= 10 ]
not_windy_flights = merged_df[ merged_df['wind_gust'] < 10 ]
mean_delay_windy = windy_flights['dep_delay_x'].mean()
mean_delay_not_windy = not_windy_flights['dep_delay_x'].mean()
print(f"Windy Flights Delay: {mean_delay_windy}")
print(f"Not-Windy Flights Delay: {mean_delay_not_windy}")

Windy Flights Delay: 8.987940449752086
Not-Windy Flights Delay: 7.610696046514664

# **PART- 2**

**SQL Questions**

**You must use sqlite3 library for SQL operations**

**Dataset Url: https://www.kaggle.com/datasets/ayeshaimran123/foodpanda-order-and-delivery-trends**


The Foodpanda Order & Delivery Trends dataset contains information about customer orders made through the Foodpanda application. It includes details such as customer information, order status, restaurant data, ratings, payment methods, and more.

Dataset description

# Tables

## 1. Customer Table

| Column          | Type    | Key         | Description                                                                                              |
|-----------------|---------|-------------|----------------------------------------------------------------------------------------------------------|
| customer_id     | TEXT    | PRIMARY KEY | Unique identifier for each customer                                                                      |
| gender          | TEXT    |             | Gender of the customer                                                                                   |
| age_group       | TEXT    |             | Categorizes customers into broad age-based segments                                                      |
| city            | TEXT    |             | Indicates the city where customer resides                                                                |
| signup_date     | TEXT    |             | Represents the date when the customers created their account on Foodpanda platform                       |
| order_frequency | INTEGER |             | nIdicates how frequently customer places orders                                                          |
| last_order_date | TEXT    |             | Date of last order                                                                                       |
| loyalty_points  | INTEGER |             | Represents the reward points earned by a customer                                                        |
| churned         | TEXT    |             | nIdicates whether customer has stopped using the Foodpanda platform after a certain period of inactivity |



## 2. Order Table

| Column          | Type    | Key     | Description                                                                                                                                                |
| --------------- | ------- | ------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- |
| order_id        | TEXT    | PRIMARY | Unique identifier for orders                                                                                                                               |
| customer_id     | TEXT    | FOREIGN | Unique identifier for customers                                                                                                                            |
| restaurant_id   | INTEGER | FOREIGN | Unique identifier for restaurants                                                                                                                          |
| order_date      | TEXT    |         | Date of order                                                                                                                                              |
| dish_name       | TEXT    |         | Indicates the type of the food item ordered by the customer                                                                                                |
| category        | TEXT    |         | Represents the cusine of the ordered dish                                                                                                                  |
| quantity        | INTEGER |         | Indicates the number of units of a particular dish ordered by the customer in a single order                                                               |
| price           | REAL    |         | Represents the total cost of the ordered dish                                                                                                              |
| payment_method  | TEXT    |         | Specifies the method used by the customer to pay for the order                                                                                             |
| rating          | INTEGER |         | Indicates the numerical rating (usually on a scale such as 1–5) given by the customer to evaluate their satisfaction with the order or delivery experience |
| rating_date     | TEXT    |         | Represents the date when the customer submitted their rating or review for the order                                                                       |
| delivery_status | TEXT    |         | Describes the final status of the order’s delivery process                                                                                                 |


## 3. Restaurant Table

| Column          | Type    | Key     | Description                        |
|-----------------|---------|---------|------------------------------------|
| restaurant_id   | INTEGER | PRIMARY | Unique indetifiers for restaurants |
| restaurant_name | TEXT    |         | Name of the restaurant             |

**Dataset path: Data/Foodpanda Analysis Dataset.csv**

In this section, you will work with the Foodpanda Order & Delivery Trends dataset, which stores information about orders made on the Foodpanda platform. You are required to read the dataset from a CSV file, build a relational database, and write code to answer the following questions. When creating the database, you must follow the table schema described above.

# Questions (50p)

1. Read the csv file and create database. (10p)
2. Find the top 3 restaurants with the highest total revenue. (revenue = quantity x price) (5p)
3. Calculate the total quantity of dishes sold by category for each restaurant. (5p)
4. List the top 5 customer with highest total spending (also show total spending value) (5p)
5. Find the average rating for each restaurant. (5p)
6. Check for duplicate orders (same customer_id+restaurant_id+order_date). (5p)
7. Find the percentage of orders by delivery status. (7p)
8. Analyze whether specific cities contribute a significantly larger portion to the total revenue compared to others. (8p)

In [14]:
full_df = pd.read_csv("Data/Foodpanda Analysis Dataset.csv")
conn = sqlite3.connect("foodpanda.db")
restaurant_columns = ['restaurant_name']
restaurants_df = full_df[restaurant_columns].drop_duplicates().reset_index(drop=True)
restaurants_df['restaurant_id'] = restaurants_df.index
restaurants_df.to_sql("Restaurant", conn, if_exists='replace', index=False)
customer_columns = [
    'customer_id', 'gender', 'age', 'city', 'signup_date', 
    'order_frequency', 'last_order_date', 'loyalty_points', 'churned'
]
customers_df = full_df[customer_columns].drop_duplicates(subset=['customer_id']).reset_index(drop=True)
customers_df.rename(columns={'age': 'age_group'}, inplace=True)
customers_df.to_sql("Customer", conn, if_exists='replace', index=False)
full_df = pd.merge(
    full_df, 
    restaurants_df,
    on='restaurant_name',
    how='left'
)
order_columns = [
    'order_id', 'customer_id', 'restaurant_id',
    'order_date', 'dish_name', 'category', 'quantity', 'price', 
    'payment_method', 'rating', 'rating_date', 'delivery_status'
]
orders_df = full_df[order_columns]
orders_df.to_sql("Orders", conn, if_exists='replace', index=False)

6000

In [11]:
query2 = """
SELECT
    r.restaurant_name,
    SUM(o.quantity * o.price) AS total_revenue
FROM
    Orders AS o
JOIN
    Restaurant AS r ON o.restaurant_id = r.restaurant_id
GROUP BY
    r.restaurant_name
ORDER BY
    total_revenue DESC
LIMIT
    3
"""

try:
    top_3_restaurants = pd.read_sql_query(query2, conn)

    print("Top 3 restaurants with the highest revenue:")
    display(top_3_restaurants)

except Exception as e:
    print(f"Query error: {e}")

Top 3 restaurants with the highest revenue:

  restaurant_name  total_revenue
0       Pizza Hut     3002380.59
1          Subway     2998014.27
2             KFC     2954233.45

In [10]:
query3 = """
SELECT
    r.restaurant_name,
    o.category,
    SUM(o.quantity) AS total_quantity
FROM
    Orders AS o
JOIN
    Restaurant AS r ON o.restaurant_id = r.restaurant_id
GROUP BY
    r.restaurant_name, o.category
ORDER BY
    r.restaurant_name, total_quantity DESC
"""

try:
    category_sales = pd.read_sql_query(query3, conn)

    print("Total quantity of dishes sold by category for each restaurant:")
    display(category_sales)

except Exception as e:
    print(f"Query error: {e}")

Total quantity of dishes sold by category for each restaurant:

   restaurant_name     category  total_quantity
0      Burger King    Fast Food             799
1      Burger King  Continental             689
2      Burger King      Italian             681
3      Burger King      Dessert             658
4      Burger King      Chinese             649
5              KFC  Continental             757
6              KFC      Chinese             754
7              KFC    Fast Food             747
8              KFC      Italian             735
9              KFC      Dessert             641
10      McDonald's      Italian             699
11      McDonald's    Fast Food             686
12      McDonald's  Continental             665
13      McDonald's      Chinese             658
14      McDonald's      Dessert             651
15       Pizza Hut  Continental             803
16       Pizza Hut      Chinese             801
17       Pizza Hut      Dessert             746
18       Pizza Hut      Italian             738
19       Pizza Hut    Fast Food             638
20          Subway      Italian             859
21          Subway    Fast Food             746
22          Subway  Continental             730
23          Subway      Dessert             715
24          Subway      Chinese             705

In [12]:
query4 = """
SELECT
    customer_id,
    SUM(quantity * price) AS total_spending
FROM
    Orders
GROUP BY
    customer_id
ORDER BY
    total_spending DESC
LIMIT
    5
"""

try:
    top_5_customers = pd.read_sql_query(query4, conn)

    print("Top 5 customer with highest total spending:")
    display(top_5_customers)

except Exception as e:
    print(f"Query error: {e}")

Top 5 customer with highest total spending:

  customer_id  total_spending
0       C3134         7496.85
1       C2515         7495.05
2       C6021         7494.65
3       C2857         7493.60
4       C3320         7491.80

In [13]:
query5 = """
SELECT
    r.restaurant_name,
    AVG(o.rating) AS average_rating
FROM
    Orders as o
JOIN
    Restaurant AS r ON o.restaurant_id = r.restaurant_id
WHERE
    o.rating IS NOT NULL
GROUP BY
    r.restaurant_name
ORDER BY
    average_rating DESC
"""

try:
    avg_ratings = pd.read_sql_query(query5, conn)

    print("Average rating for each restaurant:")
    display(avg_ratings)

except Exception as e:
    print(f"Query error: {e}")

Average rating for each restaurant:

  restaurant_name  average_rating
0          Subway        3.087302
1      McDonald's        3.002629
2             KFC        2.974673
3     Burger King        2.966116
4       Pizza Hut        2.949346

In [16]:
query6 = """
SELECT
    customer_id,
    restaurant_id,
    order_date,
    COUNT(*) AS duplicate_count
FROM
    Orders
GROUP BY
    customer_id, restaurant_id, order_date
HAVING
    duplicate_count > 1
"""

try:
    duplicate_orders = pd.read_sql_query(query6, conn)
    if len(duplicate_orders) > 0:
        print("Duplicate orders:")
        display(duplicate_orders)
    else:
        print("No duplicate orders found.")

except Exception as e:
    print(f"Query error: {e}")

No duplicate orders found.

In [19]:
query7 = """
SELECT
    delivery_status,
    COUNT(*) AS status_count,
    (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Orders)) AS percentage
FROM
    Orders
GROUP BY
    delivery_status
ORDER BY
    percentage DESC
"""

try: 
    status_percentage = pd.read_sql_query(query7, conn)

    print("Percentage of orders by delivery status:")
    display(status_percentage)

except Exception as e:
    print(f"Query error: {e}")

Percentage of orders by delivery status:

  delivery_status  status_count  percentage
0       Delivered          2060   34.333333
1         Delayed          1972   32.866667
2       Cancelled          1968   32.800000

In [20]:
query8 = """
SELECT
    c.city,
    SUM(o.quantity * o.price) AS total_revenue,
    (SUM(o.quantity * o.price) * 100.0 / (SELECT SUM(quantity * price) FROM Orders)) AS revenue_percentage
FROM
    Orders AS o
JOIN
    Customer AS c ON o.customer_id = c.customer_id
GROUP BY
    c.city
ORDER BY
    total_revenue DESC
"""

try:
    city_revenue_analysis = pd.read_sql_query(query8, conn)

    print("Revenue Distribution and Percentage According to Cities")
    display(city_revenue_analysis)
except Exception as e:
    print(f"Query error: {e}")

finally:
    if 'conn' in locals() or 'conn' in globals():
        conn.close()

Revenue Distribution and Percentage According to Cities

        city  total_revenue  revenue_percentage
0     Multan     3052313.80           21.279507
1     Lahore     2916372.35           20.331778
2   Peshawar     2906686.38           20.264251
3  Islamabad     2835310.27           19.766646
4    Karachi     2633229.28           18.357818

# PLAGIARISM

All work on assignments must be done individually. You are encouraged to discuss the given assignments with your classmates, but these discussions should be carried out in an abstract way. That is, discussions related to a particular solution to a specific probem (either in actual code or in pseudocode) will not be tolerated. In short, turning in someone else’s work (including work available on the internet), in whole or in part, as your own will be considered as a violation of academic integrity. Please note that the former conditions also hold for the material attained using AI tools, including ChatGPT, GitHub Copilot, etc.